### ISSUE TITLE
Extension not working

### ISSUE THREAD

**Issue by roys321** [rudiedirkx/Vimeo-repeat#7] opened 2017-06-23 06:04 UTC
The extension stopped working today. It was working fine till yesterday. I have the latest Google Chrome and Windows10. Seems like Vimeo is not supporting this. Icons of the Vimeo-repeat (eg Repeat, Speed)  does not appear on the video player. 
If possible, please fix this! Thanks.

**Comment by rudiedirkx** [comment] 2017-06-23 16:56
Duplicate of #6

**Closed by rudiedirkx** 2017-06-23 16:56 UTC
